name: CI
on:
  push:
    branches-ignore:
      - "gh-pages"
  pull_request:
    paths-ignore:
      - "**/*.md"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: node-cache
        uses: actions/cache@v2
        with:
          # Cache node_modules rather than the npm cache, as we rarely update npm packages.
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci --no-audit
      - run: npm run test
      - run: npm pack --dry-run --loglevel notice 2>&1 >/dev/null | sed -e 's/^npm notice //'
